# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec60ee40012b63017cd2947434e7e7caf86614d35f6028a4f255282f969fc2cc5c393bc0e9caa80311900ac7a486f1eba6ce14af76f95ec0324fb7ccb8beb9a

test:
  secret_key_base: d11b4d287b4f998841ee1e91085747a228397eb583713249eaf9272e31f385b87a03f3b7a870ab85ddfd9f54e8f66bc1713181fd46625bc9e99f59f919847970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
